/** Real, broad genre labels used as zero-network onboarding suggestions. */
export const SUGGESTED_GENRES = [
    "Рок",
    "Альтернативный рок",
    "Метал",
    "Поп",
    "Хип-хоп",
    "Электроника",
    "Инди",
    "Классика",
    "Джаз",
    "Саундтреки",
    "Русская поп-музыка",
    "Русский рок",
    "Русский рэп",
    "R&B",
    "Соул",
    "K-pop",
    "J-pop",
    "Панк",
    "Постпанк",
    "Танцевальная",
    "Хаус",
    "Техно",
    "Drum and bass",
    "Трип-хоп",
    "Эмбиент",
    "Блюз",
    "Фанк",
    "Неоклассика",
    "Фолк",
    "Кантри",
    "Регги",
    "Латино",
    "Шансон",
    "Авторская песня",
] as const;

/** Browsable groups, not extra taste signals or an imported provider taxonomy. */
export const GENRE_GROUPS = [
    {
        label: "Поп и соул",
        genres: ["Поп", "Русская поп-музыка", "R&B", "Соул", "K-pop", "J-pop"],
    },
    {
        label: "Рок и гитары",
        genres: [
            "Рок",
            "Русский рок",
            "Альтернативный рок",
            "Метал",
            "Инди",
            "Панк",
            "Постпанк",
        ],
    },
    { label: "Хип-хоп и рэп", genres: ["Хип-хоп", "Русский рэп"] },
    {
        label: "Электроника и танцы",
        genres: [
            "Электроника",
            "Танцевальная",
            "Хаус",
            "Техно",
            "Drum and bass",
            "Трип-хоп",
            "Эмбиент",
        ],
    },
    {
        label: "Джаз, классика и кино",
        genres: [
            "Джаз",
            "Блюз",
            "Фанк",
            "Классика",
            "Неоклассика",
            "Саундтреки",
        ],
    },
    {
        label: "Фолк и другие направления",
        genres: [
            "Фолк",
            "Кантри",
            "Регги",
            "Латино",
            "Шансон",
            "Авторская песня",
        ],
    },
] as const;

type SuggestedGenre = (typeof SUGGESTED_GENRES)[number];

const ARTISTS_BY_GENRE: Record<SuggestedGenre, readonly string[]> = {
    "Русская поп-музыка": [
        "Zivert",
        "Моя Мишель",
        "Дима Билан",
        "Полина Гагарина",
        "Ёлка",
        "Винтаж",
    ],
    "Русский рок": [
        "Кино",
        "ДДТ",
        "Земфира",
        "Сплин",
        "Би-2",
        "Наутилус Помпилиус",
    ],
    "Русский рэп": [
        "Баста",
        "Noize MC",
        "Oxxxymiron",
        "Каста",
        "ATL",
        "Скриптонит",
    ],
    "R&B": [
        "SZA",
        "Frank Ocean",
        "Alicia Keys",
        "Usher",
        "H.E.R.",
        "The Weeknd",
    ],
    Соул: [
        "Aretha Franklin",
        "Marvin Gaye",
        "Otis Redding",
        "Stevie Wonder",
        "Erykah Badu",
    ],
    "K-pop": ["BTS", "BLACKPINK", "TWICE", "Stray Kids", "SEVENTEEN", "aespa"],
    "J-pop": [
        "YOASOBI",
        "Ado",
        "Hikaru Utada",
        "Kenshi Yonezu",
        "Official HIGE DANdism",
    ],
    Панк: [
        "Green Day",
        "The Offspring",
        "Ramones",
        "Sex Pistols",
        "Король и Шут",
    ],
    Постпанк: [
        "Joy Division",
        "Молчат Дома",
        "The Cure",
        "Дурной Вкус",
        "Буерак",
    ],
    Танцевальная: [
        "Avicii",
        "Calvin Harris",
        "David Guetta",
        "Martin Garrix",
        "Swedish House Mafia",
    ],
    Хаус: [
        "Disclosure",
        "Daft Punk",
        "Frankie Knuckles",
        "Kerri Chandler",
        "Duke Dumont",
    ],
    Техно: [
        "Jeff Mills",
        "Carl Cox",
        "Charlotte de Witte",
        "Amelie Lens",
        "Richie Hawtin",
    ],
    "Drum and bass": [
        "Pendulum",
        "Chase & Status",
        "Sub Focus",
        "Netsky",
        "Noisia",
    ],
    "Трип-хоп": [
        "Massive Attack",
        "Portishead",
        "Tricky",
        "Morcheeba",
        "Sneaker Pimps",
    ],
    Эмбиент: [
        "Brian Eno",
        "Stars of the Lid",
        "Hammock",
        "Loscil",
        "Biosphere",
    ],
    Блюз: [
        "B.B. King",
        "Muddy Waters",
        "Howlin' Wolf",
        "John Lee Hooker",
        "Stevie Ray Vaughan",
    ],
    Фанк: ["James Brown", "Parliament", "Funkadelic", "Vulfpeck", "The Meters"],
    Неоклассика: [
        "Ludovico Einaudi",
        "Max Richter",
        "Ólafur Arnalds",
        "Nils Frahm",
        "Dustin O'Halloran",
    ],
    Фолк: ["Мельница", "Wardruna", "Fleet Foxes", "Пелагея", "The Dubliners"],
    Кантри: [
        "Johnny Cash",
        "Dolly Parton",
        "Willie Nelson",
        "Chris Stapleton",
        "Kacey Musgraves",
    ],
    Регги: [
        "Bob Marley & The Wailers",
        "Peter Tosh",
        "Jimmy Cliff",
        "Toots & The Maytals",
        "Steel Pulse",
    ],
    Латино: ["Shakira", "Bad Bunny", "J Balvin", "Juanes", "Celia Cruz"],
    Шансон: [
        "Михаил Круг",
        "Любовь Успенская",
        "Михаил Шуфутинский",
        "Вилли Токарев",
        "Александр Розенбаум",
    ],
    "Авторская песня": [
        "Булат Окуджава",
        "Владимир Высоцкий",
        "Олег Митяев",
        "Юрий Визбор",
        "Сергей Никитин",
    ],
    Рок: ["Linkin Park", "Muse", "Кино", "Foo Fighters", "Queen"],
    "Альтернативный рок": [
        "Radiohead",
        "Linkin Park",
        "Muse",
        "Paramore",
        "Arctic Monkeys",
    ],
    Метал: [
        "Rammstein",
        "Bring Me The Horizon",
        "Metallica",
        "Architects",
        "Spiritbox",
    ],
    Поп: ["Dua Lipa", "The Weeknd", "Billie Eilish", "Taylor Swift", "Zivert"],
    "Хип-хоп": [
        "Kendrick Lamar",
        "Travis Scott",
        "Noize MC",
        "Oxxxymiron",
        "A$AP Rocky",
    ],
    Электроника: [
        "Daft Punk",
        "The Prodigy",
        "Röyksopp",
        "Moderat",
        "Disclosure",
    ],
    Инди: [
        "Tame Impala",
        "Молчат Дома",
        "Florence + The Machine",
        "The xx",
        "Земфира",
    ],
    Классика: [
        "Johann Sebastian Bach",
        "Wolfgang Amadeus Mozart",
        "Ludwig van Beethoven",
        "Claude Debussy",
        "Pyotr Ilyich Tchaikovsky",
    ],
    Джаз: [
        "Miles Davis",
        "John Coltrane",
        "Ella Fitzgerald",
        "Chet Baker",
        "Nina Simone",
    ],
    Саундтреки: [
        "Hans Zimmer",
        "Ramin Djawadi",
        "Joe Hisaishi",
        "Howard Shore",
        "Hildur Guðnadóttir",
    ],
};

const EXTENDED_ARTISTS_BY_GENRE: Record<SuggestedGenre, readonly string[]> = {
    Рок: [
        "The Beatles",
        "Led Zeppelin",
        "Pink Floyd",
        "AC/DC",
        "The Rolling Stones",
        "David Bowie",
        "Red Hot Chili Peppers",
    ],
    "Альтернативный рок": [
        "Nirvana",
        "Pearl Jam",
        "Soundgarden",
        "Alice in Chains",
        "Placebo",
        "The Smashing Pumpkins",
        "Queens of the Stone Age",
    ],
    Метал: [
        "Iron Maiden",
        "Black Sabbath",
        "Judas Priest",
        "Slayer",
        "Megadeth",
        "Slipknot",
        "System of a Down",
    ],
    Поп: [
        "Madonna",
        "Michael Jackson",
        "Lady Gaga",
        "Ariana Grande",
        "Adele",
        "Bruno Mars",
        "Katy Perry",
    ],
    "Хип-хоп": [
        "Nas",
        "Jay-Z",
        "Eminem",
        "Tupac Shakur",
        "The Notorious B.I.G.",
        "J. Cole",
        "Tyler, The Creator",
    ],
    Электроника: [
        "The Chemical Brothers",
        "Justice",
        "Aphex Twin",
        "Kraftwerk",
        "Björk",
        "Moby",
        "Bonobo",
    ],
    Инди: [
        "The Strokes",
        "Vampire Weekend",
        "Arcade Fire",
        "The National",
        "Interpol",
        "Foals",
        "Alt-J",
    ],
    Классика: [
        "Frédéric Chopin",
        "Franz Schubert",
        "Sergei Rachmaninoff",
        "Igor Stravinsky",
        "Antonio Vivaldi",
        "Johannes Brahms",
        "Maurice Ravel",
    ],
    Джаз: [
        "Duke Ellington",
        "Louis Armstrong",
        "Bill Evans",
        "Thelonious Monk",
        "Herbie Hancock",
        "Charles Mingus",
        "Sarah Vaughan",
    ],
    Саундтреки: [
        "John Williams",
        "Ennio Morricone",
        "Alexandre Desplat",
        "James Horner",
        "Danny Elfman",
        "Thomas Newman",
        "Alan Silvestri",
    ],
    "Русская поп-музыка": [
        "Вера Брежнева",
        "Валерий Меладзе",
        "Сергей Лазарев",
        "Мари Краймбрери",
        "Леонид Агутин",
        "Анжелика Варум",
    ],
    "Русский рок": [
        "Алиса",
        "Агата Кристи",
        "Чайф",
        "Аквариум",
        "Мумий Тролль",
        "Ночные Снайперы",
    ],
    "Русский рэп": [
        "Гуф",
        "Хаски",
        "ЛСП",
        "Макс Корж",
        "Miyagi & Andy Panda",
        "MOT",
    ],
    "R&B": [
        "Mary J. Blige",
        "D’Angelo",
        "Solange",
        "Summer Walker",
        "Brandy",
        "Aaliyah",
    ],
    Соул: [
        "Al Green",
        "Sam Cooke",
        "Bill Withers",
        "Donny Hathaway",
        "Curtis Mayfield",
        "Diana Ross",
        "Roberta Flack",
    ],
    "K-pop": ["EXO", "Red Velvet", "NCT 127", "ITZY", "IVE", "LE SSERAFIM"],
    "J-pop": [
        "Perfume",
        "LiSA",
        "Yorushika",
        "Aimer",
        "King Gnu",
        "Aimyon",
        "Fujii Kaze",
    ],
    Панк: [
        "The Clash",
        "Bad Religion",
        "NOFX",
        "Rancid",
        "The Damned",
        "Buzzcocks",
        "Pennywise",
    ],
    Постпанк: [
        "Siouxsie and the Banshees",
        "Bauhaus",
        "Gang of Four",
        "Wire",
        "The Fall",
        "Killing Joke",
        "Motorama",
    ],
    Танцевальная: [
        "Tiësto",
        "Zedd",
        "Kygo",
        "Alesso",
        "Eric Prydz",
        "Armin van Buuren",
        "deadmau5",
    ],
    Хаус: [
        "Robin S.",
        "Crystal Waters",
        "Armand Van Helden",
        "Todd Terry",
        "Masters at Work",
        "MK",
        "Dennis Ferrer",
    ],
    Техно: [
        "Robert Hood",
        "Carl Craig",
        "Derrick May",
        "Juan Atkins",
        "Underground Resistance",
        "Adam Beyer",
        "Ben Klock",
    ],
    "Drum and bass": [
        "Andy C",
        "High Contrast",
        "London Elektricity",
        "Camo & Krooked",
        "Metrik",
        "Hybrid Minds",
        "Goldie",
    ],
    "Трип-хоп": [
        "UNKLE",
        "Lamb",
        "Hooverphonic",
        "Archive",
        "DJ Shadow",
        "Nightmares on Wax",
        "Thievery Corporation",
    ],
    Эмбиент: [
        "William Basinski",
        "Tim Hecker",
        "Grouper",
        "Steve Roach",
        "Laraaji",
        "Kaitlyn Aurelia Smith",
        "GAS",
    ],
    Блюз: [
        "Buddy Guy",
        "Albert King",
        "Freddie King",
        "Robert Johnson",
        "Etta James",
        "Son House",
        "Bessie Smith",
    ],
    Фанк: [
        "Sly & The Family Stone",
        "Kool & The Gang",
        "Earth, Wind & Fire",
        "The Ohio Players",
        "Bootsy Collins",
        "Tower of Power",
        "The Bar-Kays",
    ],
    Неоклассика: [
        "Hania Rani",
        "Joep Beving",
        "Alexandra Stréliski",
        "Sophie Hutchings",
        "Federico Albanese",
        "Dario Marianelli",
        "Peter Broderick",
    ],
    Фолк: [
        "Joan Baez",
        "Nick Drake",
        "Fairport Convention",
        "Pentangle",
        "Joni Mitchell",
        "The Chieftains",
        "Clannad",
    ],
    Кантри: [
        "Loretta Lynn",
        "Patsy Cline",
        "George Jones",
        "Merle Haggard",
        "Hank Williams",
        "Sturgill Simpson",
        "Tyler Childers",
    ],
    Регги: [
        "Burning Spear",
        "Gregory Isaacs",
        "Dennis Brown",
        "Black Uhuru",
        "Desmond Dekker",
        "Culture",
        "Max Romeo",
    ],
    Латино: [
        "Gloria Estefan",
        "Marc Anthony",
        "Ricky Martin",
        "Carlos Vives",
        "Rubén Blades",
        "Buena Vista Social Club",
        "Luis Fonsi",
    ],
    Шансон: [
        "Александр Новиков",
        "Сергей Трофимов",
        "Сергей Наговицын",
        "Ирина Круг",
        "Катя Огонёк",
        "Жека",
        "Иван Кучин",
    ],
    "Авторская песня": [
        "Александр Галич",
        "Юлий Ким",
        "Вероника Долина",
        "Татьяна и Сергей Никитины",
        "Александр Дольский",
        "Новелла Матвеева",
        "Ада Якушева",
    ],
};

const ARTISTS_BY_GENRE_KEY = new Map(
    Object.entries(ARTISTS_BY_GENRE).map(([genre, artists]) => [
        genre.toLocaleLowerCase("ru-RU"),
        [...artists, ...EXTENDED_ARTISTS_BY_GENRE[genre as SuggestedGenre]],
    ]),
);

/**
 * Build a balanced, genre-aware artist shelf. Round-robin ordering prevents
 * the first selected genre from occupying every visible slot.
 */
export function suggestArtistsForGenres(
    genres: readonly string[],
    limit: number = 12,
): string[] {
    const safeLimit = Math.max(0, Math.floor(limit));
    if (safeLimit === 0) return [];
    const groups = (genres.length > 0 ? genres : SUGGESTED_GENRES)
        .map((genre) =>
            ARTISTS_BY_GENRE_KEY.get(genre.trim().toLocaleLowerCase("ru-RU")),
        )
        .filter((artists): artists is string[] => Boolean(artists));
    if (groups.length === 0) return [];

    const suggestions: string[] = [];
    const seen = new Set<string>();
    const groupSize = Math.max(...groups.map((artists) => artists.length));
    for (let artistIndex = 0; artistIndex < groupSize; artistIndex += 1) {
        for (const artists of groups) {
            const artist = artists[artistIndex];
            if (!artist) continue;
            const key = artist.toLocaleLowerCase("ru-RU");
            if (seen.has(key)) continue;
            seen.add(key);
            suggestions.push(artist);
            if (suggestions.length >= safeLimit) return suggestions;
        }
    }
    return suggestions;
}

/** Mixed, balanced discovery shelf when no genre filter is selected. */
export const SUGGESTED_ARTISTS = suggestArtistsForGenres([], 36);
