/** UI genres mapped to Last.fm's community tags (not artist-name searches). */
export const tasteArtistTags: Readonly<Record<string, string>> = {
    Рок: "rock",
    "Альтернативный рок": "alternative rock",
    Метал: "metal",
    Поп: "pop",
    "Хип-хоп": "hip-hop",
    Электроника: "electronic",
    Инди: "indie",
    Классика: "classical",
    Джаз: "jazz",
    Саундтреки: "soundtrack",
    "Русская поп-музыка": "russian pop",
    "Русский рок": "russian rock",
    "Русский рэп": "russian rap",
    "R&B": "rnb",
    Соул: "soul",
    "K-pop": "k-pop",
    "J-pop": "j-pop",
    Панк: "punk",
    Постпанк: "post-punk",
    Танцевальная: "dance",
    Хаус: "house",
    Техно: "techno",
    "Drum and bass": "drum and bass",
    "Трип-хоп": "trip-hop",
    Эмбиент: "ambient",
    Блюз: "blues",
    Фанк: "funk",
    Неоклассика: "neo-classical",
    Фолк: "folk",
    Кантри: "country",
    Регги: "reggae",
    Латино: "latin",
    Шансон: "russian chanson",
    "Авторская песня": "bard",
};
