#!/usr/bin/env python3
"""Render a private split-stack dotenv file without printing secret values."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


KEY_RE = re.compile(r"^[A-Z_][A-Z0-9_]*$")
EXCLUDED = {
    "BACKEND_URL",
    "DATABASE_URL",
    "DATA_PATH",
    "HOSTNAME",
    "HOME",
    "MUSIC_PATH",
    "PATH",
    "PORT",
    "POSTGRES_HOST",
    "POSTGRES_PORT",
    "PWD",
    "REDIS_URL",
    "SHLVL",
    "TIDAL_SIDECAR_URL",
    "YTMUSIC_STREAMER_URL",
}
SECRET_KEYS = {
    "API_KEY_PEPPER",
    "INTERNAL_API_SECRET",
    "JWT_SECRET",
    "METRICS_TOKEN",
    "POSTGRES_PASSWORD",
    "SESSION_SECRET",
    "SETTINGS_ENCRYPTION_KEY",
}


def inspect_environment(path: Path) -> dict[str, str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    result: dict[str, str] = {}
    for item in payload[0]["Config"].get("Env", []):
        key, separator, value = item.partition("=")
        if separator and KEY_RE.fullmatch(key) and key not in EXCLUDED | SECRET_KEYS:
            result[key] = value
    return result


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def render(args: argparse.Namespace) -> str:
    inherited = inspect_environment(args.aio_inspect)
    inherited.update(inspect_environment(args.ytmusic_inspect))

    no_proxy = inherited.get("NO_PROXY", "")
    required_no_proxy = [
        "backend",
        "postgres",
        "redis",
        "tidal-streamer",
        "ytmusic-streamer",
        "audio-analyzer",
        "vibe-provider-dclap",
    ]
    no_proxy_parts = [part.strip() for part in no_proxy.split(",") if part.strip()]
    for hostname in required_no_proxy:
        if hostname not in no_proxy_parts:
            no_proxy_parts.append(hostname)
    inherited["NO_PROXY"] = ",".join(no_proxy_parts)

    suffix = "rehearsal" if args.mode == "rehearsal" else "prod"
    fixed = {
        "ANALYSIS_SPOOL_PATH": args.analysis_spool_path,
        "BACKEND_PORT": "13006" if args.mode == "rehearsal" else "3006",
        "FRONTEND_PORT": "13030" if args.mode == "rehearsal" else "3030",
        "MUSIC_PATH": args.music_path,
        "MUSIC_VOLUME_MARKER_PATH": args.music_volume_marker_path,
        "POSTGRES_PORT": "15432" if args.mode == "rehearsal" else "5432",
        "REDIS_PORT": "16379" if args.mode == "rehearsal" else "6379",
        "SOUNDSPAN_AUDIO_ANALYZER_CONTAINER_NAME": f"soundspan-{suffix}-audio-analyzer",
        "SOUNDSPAN_BIND_IP": "127.0.0.1" if args.mode == "rehearsal" else args.production_bind_ip,
        "SOUNDSPAN_DCLAP_CONTAINER_NAME": f"soundspan-{suffix}-dclap",
        "SOUNDSPAN_DB_CONTAINER_NAME": f"soundspan-{suffix}-postgres",
        "SOUNDSPAN_IMAGE_REPOSITORY": args.image_repository,
        "SOUNDSPAN_IMAGE_TAG": args.image_tag,
        "SOUNDSPAN_PULL_POLICY": "never",
        "SOUNDSPAN_REDIS_CONTAINER_NAME": f"soundspan-{suffix}-redis",
        "SOUNDSPAN_TIDAL_CONTAINER_NAME": f"soundspan-{suffix}-tidal",
        "SOUNDSPAN_YTMUSIC_CONTAINER_NAME": f"soundspan-{suffix}-ytmusic",
        "TIDAL_DATA_PATH": args.tidal_data_path,
        "YTMUSIC_DATA_PATH": args.ytmusic_data_path,
    }

    lines = ["# Generated by scripts/deploy/render-split-env.py; keep mode 0600."]
    lines.extend(f"{key}={quote(value)}" for key, value in sorted(inherited.items()))
    lines.append("# Stable secrets preserved verbatim from the AIO deployment:")
    lines.extend(args.base_env.read_text(encoding="utf-8").splitlines())
    lines.append("# Split-runtime overrides (last value wins):")
    lines.extend(f"{key}={quote(value)}" for key, value in sorted(fixed.items()))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("rehearsal", "production"), required=True)
    parser.add_argument("--base-env", type=Path, required=True)
    parser.add_argument("--aio-inspect", type=Path, required=True)
    parser.add_argument("--ytmusic-inspect", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--image-repository", required=True)
    parser.add_argument("--image-tag", required=True)
    parser.add_argument("--production-bind-ip", required=True)
    parser.add_argument("--music-path", required=True)
    parser.add_argument("--analysis-spool-path", required=True)
    parser.add_argument("--music-volume-marker-path", required=True)
    parser.add_argument("--tidal-data-path", required=True)
    parser.add_argument("--ytmusic-data-path", required=True)
    args = parser.parse_args()

    rendered = render(args)
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    descriptor = os.open(args.output, flags, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    os.chmod(args.output, 0o600)


if __name__ == "__main__":
    main()
